### ISSUE TITLE
invalid table names

### ISSUE THREAD

**Issue by danmarsden** [cursiveinc/moodle-plagiarism_origai#1]
you've used "plagiarism_origai" as the prefix on your table names in the install.xml file but unfortunately this violates the frankenstyle coding guidelines for table names:
https://moodledev.io/general/development/policies/codingstyle/frankenstyle#table-names

Note - this is a blocker for plugins db approval - you will either need to fix the table names, or change the plugin name itself from the longer form "plagiarism_originalityai" to "plagiarism_origai" if you would like to land this in the plugins db.

**Comment by cursiveinc** [comment]
resolved in new release
