### ISSUE TITLE
should the report page use a require_capability call instead of a has_capability?

### ISSUE THREAD

**Issue by danmarsden** [cursiveinc/moodle-plagiarism_origai#5]
It looks like you check "has_capability" then do some queries, but only show the report if they have the capability?
https://github.com/cursiveinc/plagiarism/blob/main/plagiarism_originalityai_report.php#L45C2-L45C14

it might be more efficient (and safer) to change that to a require_capability call?

(not a blocker for plugins db approval.)

**Comment by cursiveinc** [comment]
closed pending new release
