### ISSUE TITLE
please don't call curl_init directly 

### ISSUE THREAD

**Issue by danmarsden** [cursiveinc/moodle-plagiarism_origai#7]
Please don't initate curl_init() directly but use Moodle's own "curl" class which is a wrapper on PHP's curl functions.

Many organisations put their moodle site behind a web proxy and the internal curl wrapper takes care of this and various security settings for you.

This isn't documented all that well, but if you search the core code for curl you should find some examples of it's use.

**Comment by cursiveinc** [comment]
closed pending new release
